/*
 * This file is generated by jOOQ.
 */
package org.spin.cloud.gateway.repository;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.spin.cloud.gateway.repository.tables.GatewayRouteDefinition;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
public class XqcAdmin extends SchemaImpl {

    private static final long serialVersionUID = -1689492657;

    /**
     * The reference instance of <code>xqc_admin</code>
     */
    public static final XqcAdmin XQC_ADMIN = new XqcAdmin();


    /**
     * The table <code>xqc_admin.gateway_route_definition</code>.
     */
    public final GatewayRouteDefinition GATEWAY_ROUTE_DEFINITION = GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION;

    /**
     * No further instances allowed
     */
    private XqcAdmin() {
        super("xqc_admin", null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return new ArrayList<>(getTables0());
    }

    private List<Table<?>> getTables0() {
        return Arrays.asList(
            GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION);
    }
}
