/*
 * This file is generated by jOOQ.
 */
package org.spin.cloud.gateway.repository.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.spin.cloud.gateway.repository.tables.GatewayRouteDefinition;
import org.spin.core.gson.reflect.TypeToken;
import org.spin.core.util.JsonUtils;
import org.springframework.cloud.gateway.filter.FilterDefinition;
import org.springframework.cloud.gateway.handler.predicate.PredicateDefinition;
import org.springframework.cloud.gateway.route.RouteDefinition;

import java.net.URI;
import java.net.URISyntaxException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
public class GatewayRouteDefinitionRecord extends UpdatableRecordImpl<GatewayRouteDefinitionRecord> implements Record9<String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> {

    private static final TypeToken<ArrayList<PredicateDefinition>> PREDICATE_TYPE = new TypeToken<ArrayList<PredicateDefinition>>() {
    };

    private static final TypeToken<ArrayList<FilterDefinition>> FILTER_TYPE = new TypeToken<ArrayList<FilterDefinition>>() {
    };

    private static final long serialVersionUID = 1594730659;

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.uri</code>.
     */
    public void setUri(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.predicates</code>.
     */
    public void setPredicates(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.predicates</code>.
     */
    public String getPredicates() {
        return (String) get(2);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.filters</code>.
     */
    public void setFilters(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.filters</code>.
     */
    public String getFilters() {
        return (String) get(3);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.update_time</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.version</code>.
     */
    public void setVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.valid</code>.
     */
    public void setValid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.valid</code>.
     */
    public Integer getValid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>xqc_admin.gateway_route_definition.order_no</code>.
     */
    public void setOrderNo(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>xqc_admin.gateway_route_definition.order_no</code>.
     */
    public Integer getOrderNo() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.URI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.PREDICATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.FILTERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.VALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION.ORDER_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPredicates();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFilters();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPredicates();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFilters();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getValid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getOrderNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value2(String value) {
        setUri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value3(String value) {
        setPredicates(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value4(String value) {
        setFilters(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value7(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value8(Integer value) {
        setValid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord value9(Integer value) {
        setOrderNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GatewayRouteDefinitionRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, Integer value7, Integer value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GatewayRouteDefinitionRecord
     */
    public GatewayRouteDefinitionRecord() {
        super(GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION);
    }

    /**
     * Create a detached, initialised GatewayRouteDefinitionRecord
     */
    public GatewayRouteDefinitionRecord(String id, String uri, String predicates, String filters, LocalDateTime createTime, LocalDateTime updateTime, Integer version, Integer valid, Integer orderNo) {
        super(GatewayRouteDefinition.GATEWAY_ROUTE_DEFINITION);

        set(0, id);
        set(1, uri);
        set(2, predicates);
        set(3, filters);
        set(4, createTime);
        set(5, updateTime);
        set(6, version);
        set(7, valid);
        set(8, orderNo);
    }

    public static GatewayRouteDefinitionRecord fromRouteDefinition(RouteDefinition definition) {
        GatewayRouteDefinitionRecord gatewayRouteDefinition = new GatewayRouteDefinitionRecord();
        gatewayRouteDefinition.setId(definition.getId());
        gatewayRouteDefinition.setUri(definition.getUri().toString());
        gatewayRouteDefinition.setOrderNo(definition.getOrder());
        gatewayRouteDefinition.setPredicates(JsonUtils.toJson(definition.getPredicates()));
        gatewayRouteDefinition.setFilters(JsonUtils.toJson(definition.getFilters()));
        gatewayRouteDefinition.setValid(1);
        return gatewayRouteDefinition;
    }

    public RouteDefinition toRouteDefinition() {
        RouteDefinition definition = new RouteDefinition();
        definition.setId(getId());
        try {
            definition.setUri(new URI(getUri()));
        } catch (URISyntaxException ignore) {
            // do nothing
        }
        definition.setOrder(getOrderNo());
        List<PredicateDefinition> definitions = getPredicateDefinitions();
        if (definitions != null) {
            definition.setPredicates(definitions);
        }
        List<FilterDefinition> filterDefs = getFilterDefinitions();
        if (filterDefs != null) {
            definition.setFilters(filterDefs);
        }
        return definition;
    }

    public List<PredicateDefinition> getPredicateDefinitions() {
        if (getPredicates() != null) {
            return JsonUtils.fromJson(getPredicates(), PREDICATE_TYPE);
        }
        return null;
    }

    public List<FilterDefinition> getFilterDefinitions() {
        if (null != getFilters()) {
            return JsonUtils.fromJson(getFilters(), FILTER_TYPE);
        }
        return null;
    }
}
